### ISSUE TITLE
The city lists doesn't show anything

### ISSUE THREAD

**Issue by ktamuraasteria** [0xNF/asteria_test_uwp#23]
I run the app. Even if I input something in the Textbox of City in the `Select a City` dialog, it doesn't show anything.
Does this means you don't implement it yet because you didn't have much time?

**Comment by 0xNF** [comment]
Thanks for opening this issue.

I can assure you, of all the things I didn't have time for, I made very sure to have time to add a cities list! The cities are stored in an embedded SQLite file (`Asteria_Weather/AsteriaWeather.db`) in the `OWMCities` table. 

I can only suspect that for some reason the DB file isn't copying over to LocalStorage. At the moment, I don't know why that would be the case.

This is looking like an "It works on my computer" issue. I am currently investigating why it is happening, but reproduction is going to be a bit of a challenge, given the circumstances.

Could you confirm the following for me?

1. Did the project you cloned contain the AsteriaWeather.db file? 
1. Did the following NuGet packages get downloaded properly?
	* SQLitePCLRaw.bundle_winsqlite3
	* Microsoft.Data.Sqlite.Core (2.2.4)
	
For posterity, I have included a screenshot of the cities list as seen from my perspective.

**Comment by 0xNF** [comment]
I think I found the issue - it had to do with a race condition in the `App.xaml.cs.OnLaunched()` method regarding copying the database. It didn't manifest earlier because the Database file was pre-copied from earlier runs, and those earlier runs were in a Debug environment, giving the database copy method time to finish before it was being accessed. 

The solution, available in the most current patch (4cce18ac311056ce675edbaab28967df6605fa15) was to mark the `OnLaunched` event as `async void` and to await the copy.
